"""add checks models

Revision ID: 4ef40f626291
Revises: 1d598ab862df
Create Date: 2025-10-26 01:07:13.671821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ef40f626291"
down_revision: Union[str, Sequence[str], None] = "1d598ab862df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_request",
        sa.Column(
            "request_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "request_type",
            sa.Enum(
                "INFO",
                "PING",
                "HTTP",
                "TCP_CONNECT",
                "UDP_CONNECT",
                "DNS",
                name="requesttype",
            ),
            nullable=False,
        ),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "check_responses",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["check_request.request_id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "request_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("check_responses")
    op.drop_table("check_request")
    # ### end Alembic commands ###
