"""change ckecks to one to many

Revision ID: 49fa436f3df9
Revises: 1ee13bd33c69
Create Date: 2025-10-25 23:23:27.488792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49fa436f3df9"
down_revision: Union[str, Sequence[str], None] = "1ee13bd33c69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "check_responses", sa.Column("agent_id", sa.Uuid(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("check_responses", "agent_id")
    # ### end Alembic commands ###
