"""add latency column

Revision ID: fb2404904d9b
Revises: 4ef40f626291
Create Date: 2025-10-26 01:30:14.428968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb2404904d9b"
down_revision: Union[str, Sequence[str], None] = "4ef40f626291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "check_responses", sa.Column("latency_ms", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("check_responses", "latency_ms")
    # ### end Alembic commands ###
