"""add agents table

Revision ID: 1d598ab862df
Revises: 4213a33d4c89
Create Date: 2025-10-25 19:44:15.098097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d598ab862df"
down_revision: Union[str, Sequence[str], None] = "4213a33d4c89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "SETUP", "REVOKED", name="agentstatus"
            ),
            server_default=sa.text("'SETUP'"),
            nullable=False,
        ),
        sa.Column(
            "api_key",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("rmq_request_queue", sa.String(), nullable=False),
        sa.Column("rmq_user", sa.String(), nullable=False),
        sa.Column("rmq_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("rmq_request_queue"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agents")
    # ### end Alembic commands ###
